dbt_oracle_project:
  outputs:
    dev:
      host: orcl-db
      password: Ujjawal@12345678
      port: 1521
      protocol: tcp
      schema: DBT_STAGING
      service: FREEPDB1
      threads: 1
      type: oracle
      user: SYSTEM
  target: dev
dbt_project:
  outputs:
    prod:
      dbname: dbt_postgres
      host: db
      pass: ujjawaldbtpostgres
      port: 5432
      schema: dbt_transformed
      threads: 1
      type: postgres
      user: postgres
  target: prod
dbt_spark_project:
  outputs:
    dev:
      host: spark-cluster
      method: thrift
      port: 10000
      schema: default
      threads: 10
      type: spark
  target: dev
