version: '3.1'

services:
  dbt-services:
    build: .
    volumes:
      - ./dbt-project/dbt_project/:/home/dbt_postgres/dbt_project
      - ./dbt-project/dbt_oracle_project/:/home/dbt_oracle/dbt_oracle_project
      - ./dbt-project/dbt_spark_project/:/home/dbt_spark/dbt_spark_project
      - ./dbt-project/dbt_microsoft_sql_server:/home/dbt_mssql/dbt_microsoft_sql_server
      - .dbt:/root/.dbt/
    ports:
      - 9022:8081
    environment:
      - ORA_PYTHON_DRIVER_TYPE=thin
    networks:
      - dbt-network
    depends_on:
      - db
      - orcl-db
      - spark-cluster
      - mssql-db
  spark-cluster:
    build: ./spark-master/
    restart: always
    ports:
      - 9044:8080
      - 9055:7077
      - 9066:10000
    networks:
      - dbt-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ujjawaldbtpostgres
      POSTGRES_DB: dbt_postgres
    ports:
      - 9013:5432
    networks:
      - dbt-network
  orcl-db:
    image: container-registry.oracle.com/database/free:latest
    restart: always
    environment:
      - ORACLE_PWD=Ujjawal@12345678
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORA_PYTHON_DRIVER_TYPE=thin
    ports:
      - 9033:1521
    networks:
      - dbt-network
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Ujjawal@password"
    ports:
      - 9014:1433
    networks:
      - dbt-network

networks:
  dbt-network:
    driver: bridge
